### ISSUE TITLE
Use Flexbox for Standard Header/Nav Pattern

### ISSUE THREAD

**Issue by jordanwillis** [MarioLovato/Tea-Cozy#2]
In addition to removing that unnecessary `<div>` from your `<header>`, I wanted to recommend that you use Flexbox for the layout of this type of standard header/nav layout where your nav links are pushed all the way to the far right with logo on the left instead of a static left margin.

https://github.com/MarioLovato/Tea-Cozy/blob/master/css/style.css#L26

This is actually a perfect usecase for Flexbox because we don't want to be locked in with a set position because it will not display appropriatly across all screen sizes.  For example, I am using a widescreen 24in display and the nav links are positioned slightly to the right of the center of the page.

Here is how we can handle this type of layout with Flexbox.  First, we set the `<header>` `display` property to `flex`  and justify the content to center.  Then we can use `flex-grow` to instruct the nav to take up as much of the screen as possible which will result in the logo being pushed all the way to the far left.  Here is what I mean.

``` css
header {
  position: fixed;
  z-index: 1;
  align-items: center;
  width: 100%;
  height: 69px;
  border-bottom: 1px solid seashell;
  background-color: black;
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
}

nav {
  text-align: right;
  flex-grow: 1;
  color: pink;
}
```

Now, with the power of Flexbox, the logo and nav bar links will always appear in the correct location regardless of the screen size.
