### ISSUE TITLE
DRY CSS

### ISSUE THREAD

**Issue by jordanwillis** [MarioLovato/Tea-Cozy#6]
Your CSS is also looking pretty good.  One recommendation that I want to make is to begin practicing applying the DRY (don't repeat yourself) principle by eliminating duplicate properties/styles.  There are many techniques that can be used to write more DRY CSS, such as defining properties in a more generic selector, removing redundant properties that will already get applied due to cascade rules, or creating a class that can be re-used throughout your HTML.  Let me give you an example of a few of these.

Since many of the page components use Flexbox containers to control the layout, we can create a common class for the container and re-use it throughout your HTML.

``` css
.flex-container {
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
}
```

Now we can use the above class in your header, mission, teas of month, and locations components and delete those duplicated properties.

Another example is creating a common location class to control the styling of each location box.

``` css
.location {
  flex-basis: 280px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  padding: 10px;
  margin: 5px 20px;
  opacity: 1.0;
  background-color: black;
}
```

Then we can use this class for each location box and eliminate the duplicated properties across your 3 different location specific classes.

https://github.com/MarioLovato/Tea-Cozy/blob/de9b3b9e74230e71a0181e23ba3edb2171a38ce5/css/style.css#L126-L163

If you are up for it, see if you can go back and apply some of these techniques.  It will be well worth the practice and the investment will definitely pay huge dividends in the future.  Keep in mind that it takes practice and experience to be able to write perfectly DRY code the first time, so keep up the good work and always allocate some extra time at the end of a project to refactor toward DRYness.
